In [ ]:
# Capstone 2: NYC Rental Price Data Wrangling
**Project Goal:** The objective of this notebook is to clean and prepare the NYC rental dataset. I will perform data collection, definition, and cleaning to ensure the data is reliable for analyzing the key drivers of rental prices in New York City.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


plt.style.use('ggplot')
%matplotlib inline

In [3]:
file_name = 'NY Realstate Pricing.xlsx'
df = pd.read_excel(file_name)

print(f"Successfully loaded {df.shape[0]} rows and {df.shape[1]} columns.")
df.head()

Successfully loaded 17614 rows and 12 columns.

,F1,id,neighbourhood,latitude,longitude,room_type,price,days_occupied_in_2019,minimum_nights,number_of_reviews,reviews_per_month,availability_2020
0,0,2595,Midtown,40.75362,-73.98377,Entire home/apt,225,15,10,48,0.39,1
1,1,3831,Brooklyn,40.68514,-73.95976,Entire home/apt,89,188,1,295,4.67,1
2,2,5099,Manhattan,40.74767,-73.97500,Entire home/apt,200,362,3,78,0.60,19
3,3,5121,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,0,29,49,0.38,365
4,4,5178,Manhattan,40.76489,-73.98493,Private room,79,141,2,454,3.52,242

In [ ]:
## Data Definition
In this step, I will examine the data types, column names, and summary statistics to identify any initial issues such as missing values or logical errors.

In [4]:
print("--- Data Info ---")
df.info()

--- Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17614 entries, 0 to 17613
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   F1                     17614 non-null  int64
 1   id                     17614 non-null  int64
 2   neighbourhood          17614 non-null  object
 3   latitude               17614 non-null  float64
 4   longitude              17614 non-null  float64
 5   room_type              17614 non-null  object
 6   price                  17614 non-null  int64
 7   days_occupied_in_2019  17614 non-null  int64
 8   minimum_nights         17614 non-null  int64
 9   number_of_reviews      17614 non-null  int64
 10  reviews_per_month      17614 non-null  float64
 11  availability_2020      17614 non-null  int64
dtypes: float64(3), int64(7), object(2)
memory usage: 1.6+ MB

In [5]:
print("\n--- Summary Statistics ---")
summary = df.describe().T
summary['range'] = summary['max'] - summary['min']
display(summary)

--- Summary Statistics ---

,count,mean,std,min,25%,50%,75%,max,range
F1,17614.0,1.854756e+04,1.100072e+04,0.00000,8.192250e+03,1.949650e+04,2.868675e+04,3.559600e+04,3.559600e+04
id,17614.0,1.572032e+07,9.644155e+06,2595.00000,6.718288e+06,1.654699e+07,2.407707e+07,3.056528e+07,3.056269e+07
latitude,17614.0,4.072675e+01,5.698110e-02,40.50868,4.068604e+01,4.072054e+01,4.076313e+01,4.090804e+01,3.993600e-01
longitude,17614.0,-7.394773e+01,5.021280e-02,-74.23986,-7.398094e+01,-7.395305e+01,-7.393068e+01,-7.372179e+01,5.180700e-01
price,17614.0,1.454555e+02,1.949907e+02,0.00000,7.000000e+01,1.090000e+02,1.700000e+02,9.999000e+03,9.999000e+03
days_occupied_in_2019,17614.0,1.795177e+02,1.302020e+02,0.00000,3.500000e+01,1.980000e+02,3.010000e+02,3.640000e+02,3.640000e+02
minimum_nights,17614.0,7.392926e+00,1.923387e+01,1.00000,2.000000e+00,3.000000e+00,5.000000e+00,1.125000e+03,1.124000e+03
number_of_reviews,17614.0,5.612899e+01,6.597237e+01,1.00000,9.000000e+00,3.300000e+01,7.900000e+01,6.750000e+02,6.740000e+02
reviews_per_month,17614.0,1.607060e+00,1.635528e+00,0.01000,3.400000e-01,1.060000e+00,2.460000e+00,1.925000e+01,1.924000e+01
availability_2020,17614.0,1.541548e+02,1.380797e+02,0.00000,8.000000e+00,1.250000e+02,3.090000e+02,3.650000e+02,3.650000e+02

In [6]:
print("\n--- Categorical Analysis ---")
print(f"Neighbourhoods count: {df['neighbourhood'].nunique()}")
print(f"Room types available: {df['room_type'].unique()}")

--- Categorical Analysis ---
Neighbourhoods count: 186
Room types available: ['Entire home/apt' 'Private room' 'Shared room' 'Hotel room']

In [7]:
duplicates = df.duplicated(subset=['id']).sum()
print(f"\nNumber of duplicate listing IDs: {duplicates}")

Number of duplicate listing IDs: 0

In [ ]:
## Data Cleaning
Based on the initial inspection, I will perform the following cleaning steps:
1. **Drop Redundant Columns**: Remove 'F1' as it is just an index from the source file.
2. **Handle Inconsistent Data**: Check for $0 prices or unrealistic minimum nights.
3. **Handle Missing Values**: Although the initial check showed no nulls, I will re-verify.

In [8]:
if 'F1' in df.columns:
    df.drop(columns=['F1'], inplace=True)
    print("Column 'F1' dropped.")

Column 'F1' dropped.

In [9]:
zero_prices = df[df['price'] == 0]
print(f"Records with price $0: {len(zero_prices)}")

Records with price $0: 7

In [10]:
if len(zero_prices) > 0:
    df = df[df['price'] > 0]
    print("Zero-price records removed.")

Zero-price records removed.

In [11]:
print("\nMissing values per column:")
print(df.isnull().sum())

Missing values per column:
id                       0
neighbourhood            0
latitude                 0
longitude                0
room_type                0
price                    0
days_occupied_in_2019    0
minimum_nights           0
number_of_reviews        0
reviews_per_month        0
availability_2020        0
dtype: int64

In [12]:
df.to_csv('NYC_Rental_Cleaned.csv', index=False)
print("\nData Wrangling stage complete. Final shape:", df.shape)

Data Wrangling stage complete. Final shape: (17607, 11)

In [13]:
df_test = pd.read_csv('NYC_Rental_Cleaned.csv')
print(f"Verified rows: {len(df_test)}")
display(df_test.head())

Verified rows: 17607

,id,neighbourhood,latitude,longitude,room_type,price,days_occupied_in_2019,minimum_nights,number_of_reviews,reviews_per_month,availability_2020
0,2595,Midtown,40.75362,-73.98377,Entire home/apt,225,15,10,48,0.39,1
1,3831,Brooklyn,40.68514,-73.95976,Entire home/apt,89,188,1,295,4.67,1
2,5099,Manhattan,40.74767,-73.97500,Entire home/apt,200,362,3,78,0.60,19
3,5121,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,0,29,49,0.38,365
4,5178,Manhattan,40.76489,-73.98493,Private room,79,141,2,454,3.52,242

In [ ]:
## Data Wrangling Summary
In this initial stage, I successfully:
1. **Identified Data Issues**: Found that the 'F1' column was a redundant index and identified $0 price entries as data errors.
2. **Cleaned Data**: Dropped irrelevant columns and filtered out invalid price records.
3. **Data Integrity**: Confirmed that each 'id' is unique and there are no missing values across the 17,000+ records.
4. **Output**: Saved the clean dataset as `NYC_Rental_Cleaned.csv` for the upcoming Exploratory Data Analysis (EDA) phase.

**Next Step**: Will focus on EDA to visualize price distributions across different NYC neighborhoods and room types.